// Copyright 2018 Developers of the Rand project.
// Copyright 2013 The Rust Project Developers.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! A wrapper around another PRNG that reseeds it after it
//! generates a certain number of random bytes.

use core::mem::size_of_val;

use super::std::Core;
use super::{SysError, SysRng};
use rand_core::SeedableRng;
use rand_core::block::{BlockRng, Generator};

type Results = <Core as Generator>::Output;

/// A wrapper around any PRNG that implements [`Generator`], that adds the
/// ability to reseed it.
pub struct ReseedingRng(pub BlockRng<ReseedingCore>);

impl ReseedingRng {
    /// Create a new `ReseedingRng` from an existing PRNG, combined with a RNG
    /// to use as reseeder.
    ///
    /// `threshold` sets the number of generated bytes after which to reseed the
    /// PRNG. Set it to zero to never reseed based on the number of generated
    /// values.
    pub fn new(threshold: u64) -> Result<Self, SysError> {
        Ok(ReseedingRng(BlockRng::new(ReseedingCore::new(threshold)?)))
    }

    /// Immediately reseed the generator
    ///
    /// This discards any remaining random data in the cache.
    pub fn reseed(&mut self) -> Result<(), SysError> {
        self.0.reset_and_skip(0);
        self.0.core.reseed()
    }
}

pub struct ReseedingCore {
    inner: Core,
    threshold: i64,
    bytes_until_reseed: i64,
}

impl Generator for ReseedingCore {
    type Output = Results;

    fn generate(&mut self, results: &mut Results) {
        if self.bytes_until_reseed <= 0 {
            // We get better performance by not calling only `reseed` here
            // and continuing with the rest of the function, but by directly
            // returning from a non-inlined function.
            return self.reseed_and_generate(results);
        }
        let num_bytes = size_of_val(results);
        self.bytes_until_reseed -= num_bytes as i64;
        self.inner.generate(results);
    }
}

impl ReseedingCore {
    /// Create a new `ReseedingCore`.
    ///
    /// `threshold` is the maximum number of bytes produced by
    /// [`Generator::generate`] before attempting reseeding.
    fn new(threshold: u64) -> Result<Self, SysError> {
        // Because generating more values than `i64::MAX` takes centuries on
        // current hardware, we just clamp to that value.
        // Also we set a threshold of 0, which indicates no limit, to that
        // value.
        let threshold = if threshold == 0 {
            i64::MAX
        } else if threshold <= i64::MAX as u64 {
            threshold as i64
        } else {
            i64::MAX
        };

        let inner = Core::try_from_rng(&mut SysRng)?;

        Ok(ReseedingCore {
            inner,
            threshold,
            bytes_until_reseed: threshold,
        })
    }

    /// Reseed the internal PRNG.
    fn reseed(&mut self) -> Result<(), SysError> {
        Core::try_from_rng(&mut SysRng).map(|result| {
            self.bytes_until_reseed = self.threshold;
            self.inner = result
        })
    }

    #[inline(never)]
    fn reseed_and_generate(&mut self, results: &mut Results) {
        trace!("Reseeding RNG (periodic reseed)");

        let num_bytes = size_of_val(results);

        if let Err(e) = self.reseed() {
            warn!("Reseeding RNG failed: {}", e);
            let _ = e;
        }

        self.bytes_until_reseed = self.threshold - num_bytes as i64;
        self.inner.generate(results);
    }
}
